server:
  port: 8881
spring:
  application:
    name: config-client
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}